from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score


news = fetch_20newsgroups(subset='all')
print(news.keys())


new_text = ['Osteoarthritis is an inflammatory condition that impacts people’s joints and mobility.Treatment often focuses on symptom management, but researchers are still working to fully understand the condition and potential preventative measures.A​ recent study published in Annals of the Rheumatic Diseases looked at how osteoarthritis may be related to asthma or atopic dermatitis (commonly known as eczema). These conditions are forms of atopic disease.Researchers said they found that people with atopic dermatitis or asthma may be at a higher risk for developing osteoarthritis.They said further understanding of the allergic pathways involved could help prevent and treat osteoarthritis.',
            'Ad Astra is your doorway to new worlds! The multi-award-winning magazine of the National Space Society, Ad Astra is dedicated the creation of a spacefaring civilization. That dream begins with you. We offer our readers the chance to discover the fields of space exploration and development in a manner that is insightful and comprehensible. Each regular issue is filled with 60 pages of space content with minimal advertising. Whether you read in print or digital versions, you’ll receive a glimpse of ongoing human expansion into the final frontier. No other magazine offers deeper dives or more insider insights than Ad Astra. Purchase a subscription now, and start your voyage thorough the stars!',
            'Like the Jeep Gladiator and new Chevrolet Colorado, the 2024 Ranger has eschewed different cab and bed sizes, as it\'s available only with a four-door crew cab and a five-foot bed.Riding on an upgraded version of Ford T6 platform that also underpins the Bronco, the wheelbase has grown 1.9 inches, but overall length is basically unchanged (technically, it shrunk by 0.2 inch). In effect the front wheels have moved closer to the front bumper, reducing its overhang by 1.9 inches and improving approach angle.The rear suspension remains leaf springs on the Ranger (see Raptor details below), but the shocks have moved outboard closer to the wheels, making them less prone to encountering trail debris.Overall width is up 2.3 inches, netting improvements in cab space and bed storage, which can now accommodate a four-foot sheet of drywall between the wheelhouses.',
            'The new store features a Padang Light stone floor and a timber veneer-clad wall — sustainably and locally sourced within China — that maximizes visibility within the store.Visitors can explore the latest Apple products and accessories, get shopping help from Apple Specialists, choose monthly financing options, and receive personal technical advice and Genius support. Apple MixC Shenzhen also has an Apple Pickup station, which blends together the best of online and in-store shopping experiences for customers in China. The dedicated area makes it easier for customers to order online and collect their devices in-store at a convenient time.Apple MixC Shenzhen will be an exciting space for customers to learn, create, and be inspired. Today at Apple programming will take place in a roundtable setting for a more personalized experience, allowing customers to go further with their passions and the products they love. Programming will feature a powerful curation of Apple-led sessions across photography, videography, art and design, music, and coding.',
            'Rogue Initiative Studios was founded in 2015 by alumni from a number of leading game companies, including Activision and Sony. CEO/creative director Pete Blumel has spent more than 25 years working in feature film, animation, immersive reality and triple-A games. He was a part of Activision’s Infinity Ward game development studio, where he held a key role in the creation of the Call of Duty: Modern Warfare franchise.',
            'Windows 11 was released on Oct. 5, 2021, over six years after Windows 10 made its debut. Microsoft recently released the first major update for the OS — Windows 11 version 22H2 — but we\'ve heard the next thing on the cards could very well be Windows 12. It sounds like Microsoft is doing away with major annual updates, and instead going for a big, new version of Windows every three years, similar to what used to happen before Windows 10.Microsoft hasn\'t officially announced a new version of Windows. In fact, it\'s downplayed reports we\'ve heard about Windows 12. Officially, the company is committed to annual updates and smaller feature updates for Windows 11. Still, it\'s never too early to start looking ahead, and there\'s a good chance we\'ll see a follow-up to Windows 11 at some point in the future. Let\'s take a closer look at what we expect for now.',
            'Everyone dreams of exploring the globe… and if you want to do it on two-wheels, you need to be armed with a bike ready to take on any challenge.At this point most will default to the BMW GS Adventure, but a GSA is nudging 270kg, which is a lot of bulk to take up a trail. If you are serious about heading off into the wilds – or just a weekend away – something a bit more manageable can make sense.Billed by Yamaha as the ‘ultimate long-distance adventure bike’ the Ténéré World Raid aims to take on global exploration. With a big-capacity 23-litre tank and beefed-up suspension, the Raid is a proper big-mile explorer with a price that’s reasonably low thanks to a basic nature devoid of fussy electronics. KTM, on the other hand, have decided the modern explorer requires every bit of tech possible.',
            'It’s a strong word, panic. There are words that slowly lead up to panic: worry, concern, fret, stress. But panic? That’s when you know you’re freaking out. That’s when you know it’s officially going bad.It is only May 10. It’s probably too early for any team to panic. (Remember, the Phillies were 13-16 entering May 10 of last year and ended up in the World Series.) But that doesn’t mean teams, and their fans, aren’t doing that very thing. The teams with the highest propensity for panicking are the ones with the highest expectations coming into the season, and, it’s fair to say, any team that made the playoffs last year has the same high expectations for 2023.But for certain clubs -- seven teams, to be exact -- 2023 hasn’t exactly gotten off to the roaring start they were hoping for. How panicked should they and their fans be? Here’s a look at the seven teams who were in the playoffs last year but would not be if the season started today (entering Wednesday’s games), ranked by the level of panic they should all be feeling.',
            'Documents for EPC9186, as it will be known, are not available yet, but the company promises operation from 14V to 80V for “applications such as electric scooters, small electric vehicles and agricultural machinery” in addition to the items above.The design uses four of its EPC2302 transistors in parallel per switch position, so eight per half-bridge and 24 per board, and can deliver a peak of 200A.On-board are gate drivers, regulated auxiliary power rails for housekeeping, protection circuits, and sensing for voltage, temperature and current sense – both phase and leg shunt current sensing is supported. And the same board can be re-configured for multi-phase dc-dc conversion.“GaN-based inverters increase motor efficiency and can increase power capability without increasing size” claimed EPC CEO Alex Lidow. “This enables motor systems that are smaller, lighter, less noisy, have more torque, more range, and greater precision for a wide range of consumer and industrial applications.”',
            'Mass demonstrations in 2011 and 2012 called for an end to corruption and for reforms to improve economic and political freedom. Protests have continued steadily over the past decade, taking place even last month amidst the deadly pandemic. The original demands of 2011 and 2012—a curb on rampant corruption, the creation of jobs, an end to regressive taxes and subsidy cuts, and more representative government—have continued to echo through the streets with no real reform initiated in response. In recent years, protestors and activists have faced harsh crackdowns and prison sentences for exercising free speech and for the crime of naming the government’s own failures. This is the sad reality that is, and has been for some time, under gag order in Jordan.']



vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(news.data)
y_train = news.target


clf = MultinomialNB()
clf.fit(X_train, y_train)


X_new = vectorizer.transform(new_text)
y_pred = clf.predict(X_new)


print(y_pred)


y_test = [13, 14, 7, 4, 1, 2, 8, 9, 12, 17]
acc = accuracy_score(y_test, y_pred)
print('Accuracy:', acc)

